[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = '0.3.1'
auto_detect_solc = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
